version: '3.1'
services:
  stats-server:
    build: ./stats-server/stats-svc
    image: stats_svc_image
    container_name: stats_svc_container
    depends_on:
      - stats-db
      - rabbitmq
      - ewm-service
    ports:
      - "9090:9090"
    environment:
      - DB_NAME=stats-db
      - DB_HOST=stats-db
      - DB_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - Q_FOR_SAVE_NAME=saveHit
      - Q_FOR_GET_STATS_NAME=getStats

  stats-db:
    image: postgres:14-alpine
    container_name: stats_svc_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./ewm-main-svc
    image: ewm_main_svc_image
    container_name: ewm_main_svc_container
    depends_on:
      - ewm-db
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=ewm-db
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - Q_FOR_SAVE_NAME=saveHit
      - Q_FOR_GET_STATS_NAME=getStats
      - EXCHANGE_NAME=mainStats
      - RK_FOR_SAVE_HITS=saveHit
      - RK_FOR_GET_STATS=getStats

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_main_svc_db_container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"