version: '3.1'
services:
  stats-server:
    build: ./stats-server/stats-svc
    image: stats_svc_image
    container_name: stats_svc_container
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - DB_NAME=stats-db
      - DB_HOST=stats-db
      - DB_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats_svc_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./ewm-main-svc
    image: ewm_main_svc_image
    container_name: ewm_main_svc_container
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=ewm-db
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_main_svc_db_container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
